version: '3.7'

services:
  api:
    image: apigqlirapa
    container_name: apigqlirapa
    restart: always
    build: .
    ports:
      - '5410:5410'
    environment:
      - PORT=5410
      - MONGODB_URI=mongodb://172.26.237.1:27020/irapacommerce
    volumes:
      - .:/app
    depends_on:
      - mongo_db
    networks:
      - ecbackend

  mongo_db:
    image: mongo:5.0.6-focal # nombre de la imagen
    container_name: mdbirapa
    restart: always
    ports:
      - '27020:27017'
    volumes:
      - /home/pedro/node/mongodb/irapa:/data/db
    networks:
      - ecbackend

networks:
  ecbackend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.237.0/24
          gateway: 172.26.237.1
